# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyticalmodel.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalyticalModel(object):
    def setupUi(self, AnalyticalModel):
        AnalyticalModel.setObjectName("AnalyticalModel")
        AnalyticalModel.setWindowModality(QtCore.Qt.NonModal)
        AnalyticalModel.setEnabled(True)
        AnalyticalModel.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("analytics.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AnalyticalModel.setWindowIcon(icon)
        AnalyticalModel.setSizeGripEnabled(True)
        AnalyticalModel.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(AnalyticalModel)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputTableWidget = QtWidgets.QTableWidget(AnalyticalModel)
        self.inputTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.inputTableWidget.setObjectName("inputTableWidget")
        self.inputTableWidget.setColumnCount(0)
        self.inputTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.inputTableWidget, 1, 0, 1, 8)
        self.label_2 = QtWidgets.QLabel(AnalyticalModel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.deleteVariantButton = QtWidgets.QPushButton(AnalyticalModel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteVariantButton.sizePolicy().hasHeightForWidth())
        self.deleteVariantButton.setSizePolicy(sizePolicy)
        self.deleteVariantButton.setMinimumSize(QtCore.QSize(0, 35))
        self.deleteVariantButton.setObjectName("deleteVariantButton")
        self.gridLayout.addWidget(self.deleteVariantButton, 2, 4, 1, 1)
        self.calculateButton = QtWidgets.QPushButton(AnalyticalModel)
        self.calculateButton.setMinimumSize(QtCore.QSize(0, 35))
        self.calculateButton.setAutoFillBackground(False)
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout.addWidget(self.calculateButton, 2, 7, 1, 1)
        self.addVariantButton = QtWidgets.QPushButton(AnalyticalModel)
        self.addVariantButton.setMinimumSize(QtCore.QSize(0, 35))
        self.addVariantButton.setObjectName("addVariantButton")
        self.gridLayout.addWidget(self.addVariantButton, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(AnalyticalModel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.outputTableWidget = QtWidgets.QTableWidget(AnalyticalModel)
        self.outputTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.outputTableWidget.setObjectName("outputTableWidget")
        self.outputTableWidget.setColumnCount(0)
        self.outputTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.outputTableWidget, 4, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(AnalyticalModel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.k1LineEdit = QtWidgets.QLineEdit(AnalyticalModel)
        self.k1LineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.k1LineEdit.setObjectName("k1LineEdit")
        self.gridLayout.addWidget(self.k1LineEdit, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(AnalyticalModel)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.deltaLineEdit = QtWidgets.QLineEdit(AnalyticalModel)
        self.deltaLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deltaLineEdit.setObjectName("deltaLineEdit")
        self.gridLayout.addWidget(self.deltaLineEdit, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(AnalyticalModel)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.k2LineEdit = QtWidgets.QLineEdit(AnalyticalModel)
        self.k2LineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.k2LineEdit.setObjectName("k2LineEdit")
        self.gridLayout.addWidget(self.k2LineEdit, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(AnalyticalModel)
        QtCore.QMetaObject.connectSlotsByName(AnalyticalModel)
        AnalyticalModel.setTabOrder(self.k1LineEdit, self.k2LineEdit)
        AnalyticalModel.setTabOrder(self.k2LineEdit, self.deltaLineEdit)
        AnalyticalModel.setTabOrder(self.deltaLineEdit, self.inputTableWidget)
        AnalyticalModel.setTabOrder(self.inputTableWidget, self.deleteVariantButton)
        AnalyticalModel.setTabOrder(self.deleteVariantButton, self.addVariantButton)
        AnalyticalModel.setTabOrder(self.addVariantButton, self.calculateButton)
        AnalyticalModel.setTabOrder(self.calculateButton, self.outputTableWidget)

    def retranslateUi(self, AnalyticalModel):
        _translate = QtCore.QCoreApplication.translate
        AnalyticalModel.setWindowTitle(_translate("AnalyticalModel", "Аналитическая модель"))
        self.label_2.setText(_translate("AnalyticalModel", "Результаты моделирования"))
        self.deleteVariantButton.setText(_translate("AnalyticalModel", "Удалить вариант"))
        self.calculateButton.setText(_translate("AnalyticalModel", "Моделирование"))
        self.addVariantButton.setText(_translate("AnalyticalModel", "Добавить вариант"))
        self.label.setText(_translate("AnalyticalModel", "Исходные данные"))
        self.label_3.setToolTip(_translate("AnalyticalModel", "<html><head/><body><p><span style=\" font-size:12pt;\">При некорректном вводе используется значение по умолчанию, которое равно 0.99995</span></p></body></html>"))
        self.label_3.setText(_translate("AnalyticalModel", "K1"))
        self.k1LineEdit.setToolTip(_translate("AnalyticalModel", "<html><head/><body><p><span style=\" font-size:12pt;\">При некорректном вводе используется значение по умолчанию = 0.99995</span></p></body></html>"))
        self.k1LineEdit.setText(_translate("AnalyticalModel", "0.99995"))
        self.label_5.setToolTip(_translate("AnalyticalModel", "<html><head/><body><p><span style=\" font-size:12pt;\">При некорректном вводе используется значение по умолчанию, которое равно 0.0009</span></p></body></html>"))
        self.label_5.setText(_translate("AnalyticalModel", "Δ"))
        self.deltaLineEdit.setText(_translate("AnalyticalModel", "0.0009"))
        self.label_4.setToolTip(_translate("AnalyticalModel", "<html><head/><body><p><span style=\" font-size:12pt;\">При некорректном вводе используется значение по умолчанию, которое равно 1000</span></p></body></html>"))
        self.label_4.setText(_translate("AnalyticalModel", "K2"))
        self.k2LineEdit.setText(_translate("AnalyticalModel", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnalyticalModel = QtWidgets.QDialog()
    ui = Ui_AnalyticalModel()
    ui.setupUi(AnalyticalModel)
    AnalyticalModel.show()
    sys.exit(app.exec_())

